name: solmana-backend

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
    branches:
      - main

jobs:
  deploy-production:
    if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production server
        run: |
          sudo apt-get update -yqq
          sudo apt-get install openssh-client sshpass -yqq
          sshpass -p ${{ secrets.SOLMANA_SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no -T ${{ secrets.SOLMANA_SERVER_USER }}@${{ secrets.SOLMANA_SERVER_IP }} 'cd api.solmana.org && git stash && git pull && composer install -n && composer dump-autoload -n && php artisan migrate --force && php artisan config:cache && exit'
